# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YTKASfpP8UdYlN8wEq5Rr8OwnaqFjvtX
"""

import math

# PalmerPenguinsM.py3
# Pamela Brauda
# 10/04/2026
# Uses lists and formatted output to analyze Palmer Penguin statistics.

#Constants representing the names and total of species
SP_CHINSTRAP = "Chinstrap"
SP_GENTOO = "Gentoo"
SP_ADELIE = "Adelie"

NUM_CHINSTRAP = 68
NUM_GENTOO = 123
NUM_ADELIE = 151

species_names = [
    SP_CHINSTRAP,
    SP_GENTOO,
    SP_ADELIE
]

species_counts = [
    NUM_CHINSTRAP,
    NUM_GENTOO,
    NUM_ADELIE
]

#Calculating the number of penguin species
total_species = len(species_names)

#Calculating the toltal number of penguins.
total_penguins = sum(species_counts)

#Calculating the average number of penguins per species.
average_penguins = total_penguins /total_species
average_penguins_rounded_up = math.ceil(average_penguins)

#Calculating the species percentage using list indexes.
chinstrap_percent = (species_counts[0] / total_penguins) * 100
gentoo_percent = (species_counts[1] / total_penguins) * 100
adelie_percent = (species_counts[2] / total_penguins) * 100

##Calculating the species with the most and fewest oberservations.
largest_count = max(species_counts)
smallest_count = min(species_counts)


largest_index = species_counts.index(largest_count)
smallest_index = species_counts.index(smallest_count)

largest_species = species_names[largest_index]
smallest_species = species_names[smallest_index]




#Output the names with introduction text
print("Introducing the Palmer Penguins:")
print("\t" + SP_CHINSTRAP + "!")
print("\t" + SP_GENTOO + "!")
print("and last but not least...")
print("\t" + SP_ADELIE + "!")
print()

#Output of calcutions.
print(f"There are a total of {total_species} penguin species in this dataset.")
print(f"There are a total of {total_penguins} penguin in this dataset.")
print(f"The average number of penguins per species is {average_penguins}.")
print(f"The average rounded up is {average_penguins_rounded_up} penguins.")
print()
print("Chinstrap:", NUM_CHINSTRAP, f"({chinstrap_percent:.2f}%)")
print("Gentoo:", NUM_GENTOO, f"({gentoo_percent:.2f}%)")
print("Adelie:", NUM_ADELIE, f"({adelie_percent:.2f}%)")
print()
print("The species with the most observations is " +
      largest_species + " with " + str(largest_count) + " penguins.")
print("The species with the fewest observations is " +
      smallest_species + " with " + str(smallest_count) + " penguins.")